### ISSUE TITLE
Quick question: is it possible to order hooks?

### ISSUE THREAD

**Issue by ghost** [barrel-db/hooks#6]
Hello, 
just a quick question, are all the hooks applied in parallel or is it possible to apply them sequentially (so we can order them) ?

**Comment by benoitc** [comment]
sorry for the late answer, I was mostly offline. I'm not sure what do you meanly applying them sequentially. When a hook is executed it will execute all functions attached to it in the order they have been added. Otherwise each hooks have its own execution time. Also all hooks are executed synchronously in the process that call it. 

Hope it answers to your question.

**Comment by ghost** [comment]
Perfect, thank you Benoit, I'll give it a try!

**Comment by ghost** [comment]
arf, no luck it's erlang 18.3 or 20.0, I'm stuck on 17 for now

**Comment by benoitc** [comment]
him there is a way to make it compatible using https://github.com/tsloughter/merl . Maybe that could be done..
